import { Category, Tool } from './types';

export const SITE_CONFIG = {
  name: "AI Nexus",
  tagline: "The Best AI Tools — Reviewed & Ranked",
  bio: "I test every tool personally. Every link is a free trial. No fluff, no sponsorships.",
  instagramUrl: "https://instagram.com/ainexustools",
  email: "hello@ainexus.tools",
  siteUrl: "https://ainexus-tools.netlify.app",
};

export const TOOLS: Tool[] = [
  // --- WRITING ---
  {
    id: 'w1', slug: 'jasper',
    name: 'Jasper', tagline: 'The AI writing assistant for marketing teams',
    description: 'Jasper is the most powerful AI writing tool for marketing teams. Create blog posts, ad copy, emails, and social content 10x faster with brand voice controls.',
    category: Category.WRITING, affiliateLink: 'https://jasper.ai?fpr=yourlink',
    iconName: 'PenTool', color: '#818cf8', accentColor: '#6366f1',
    userBadge: 'Most popular', pricing: 'From $39/month', bestFor: 'Marketing teams & agencies',
    features: ['Brand voice controls', '50+ templates', 'SEO mode', 'Multi-language support'],
    pros: ['Best brand voice consistency', 'Huge template library', 'Integrates with Surfer SEO'],
    cons: ['Expensive for solo creators', 'Requires learning curve'],
  },
  {
    id: 'w2', slug: 'copy-ai',
    name: 'Copy.ai', tagline: 'Generate marketing copy in seconds',
    description: 'Copy.ai uses GPT-4 to generate high-converting marketing copy, blog outlines, product descriptions, and emails in seconds.',
    category: Category.WRITING, affiliateLink: 'https://copy.ai?via=yourlink',
    iconName: 'Copy', color: '#a3e635', accentColor: '#65a30d',
    userBadge: 'Free plan ✓', pricing: 'Free + $36/month', bestFor: 'Solopreneurs & freelancers',
    features: ['90+ copywriting tools', 'Free forever plan', 'Workflow automation', 'Brand voice'],
    pros: ['Generous free tier', 'Very fast output', 'Great for short-form copy'],
    cons: ['Long-form needs editing', 'Outputs can feel generic'],
  },
  {
    id: 'w3', slug: 'writesonic',
    name: 'Writesonic', tagline: 'SEO-optimised AI writing for blogs & ads',
    description: 'Writesonic creates SEO-friendly blog posts, Facebook ads, Google ads, and product descriptions. Powered by GPT-4 with a built-in AI chatbot.',
    category: Category.WRITING, affiliateLink: 'https://writesonic.com?via=yourlink',
    iconName: 'FileText', color: '#a855f7', accentColor: '#7c3aed',
    userBadge: 'Free plan ✓', pricing: 'Free + from $16/month', bestFor: 'Bloggers & content marketers',
    features: ['AI Article Writer 6.0', 'Chatsonic (ChatGPT alternative)', 'Botsonic chatbot builder', 'SEO checker'],
    pros: ['Best value for bloggers', 'Affordable paid plans', 'Free trial available'],
    cons: ['Quality varies by template', 'UI can feel cluttered'],
  },
  {
    id: 'w4', slug: 'rytr',
    name: 'Rytr', tagline: 'Fast, affordable AI writing for everyone',
    description: 'Rytr is one of the most affordable AI writing tools. Write bios, Facebook ads, landing page copies, and emails in 30+ languages.',
    category: Category.WRITING, affiliateLink: 'https://rytr.me?via=yourlink',
    iconName: 'Type', color: '#fca5a5', accentColor: '#ef4444',
    userBadge: 'Best for beginners', pricing: 'Free + $9/month', bestFor: 'Budget-conscious creators',
    features: ['40+ use cases', '30+ languages', 'Chrome extension', 'Plagiarism checker'],
    pros: ['Very affordable', 'Great free plan', 'Simple to use'],
    cons: ['Limited long-form output', 'Less accurate than premium tools'],
  },
  {
    id: 'w5', slug: 'quillbot',
    name: 'Quillbot', tagline: 'Paraphrase, summarise & improve your writing',
    description: 'Quillbot is the best AI paraphrasing tool. Rewrite sentences, summarise articles, check grammar, and detect plagiarism all in one platform.',
    category: Category.WRITING, affiliateLink: 'https://quillbot.com?via=yourlink',
    iconName: 'Wand2', color: '#4ade80', accentColor: '#16a34a',
    userBadge: 'Free plan ✓', pricing: 'Free + $9.95/month', bestFor: 'Students & researchers',
    features: ['7 paraphrasing modes', 'Summariser', 'Grammar checker', 'Citation generator'],
    pros: ['Excellent free tier', 'Best paraphrasing quality', 'Easy to use'],
    cons: ['Not for original content creation', 'Premium needed for best modes'],
  },
  {
    id: 'w9', slug: 'frase',
    name: 'Frase.io', tagline: 'Research, write & optimise SEO content fast',
    description: 'Frase helps you create SEO-optimised content in minutes. Research top-ranking pages, build content briefs, and write with AI — all in one workflow.',
    category: Category.WRITING, affiliateLink: 'https://frase.io?via=yourlink',
    iconName: 'Search', color: '#2dd4bf', accentColor: '#0d9488',
    userBadge: 'SEO pick', pricing: 'From $15/month', bestFor: 'SEO writers & content teams',
    features: ['SERP analysis', 'AI content briefs', 'Topic scoring', 'AI writer'],
    pros: ['Best SEO content workflow', 'Huge time saver'],
    cons: ['Not for non-SEO writing', 'Word limits on lower plans'],
  },

  // --- IMAGE ---
  {
    id: 'i2', slug: 'leonardo-ai',
    name: 'Leonardo.ai', tagline: 'Production-quality AI image generation',
    description: 'Leonardo.ai creates stunning, production-quality visual assets with unprecedented creative control. Train your own models and generate consistent characters.',
    category: Category.IMAGE, affiliateLink: 'https://leonardo.ai/?via=yourlink',
    iconName: 'Wand2', color: '#c084fc', accentColor: '#9333ea',
    userBadge: 'Free plan ✓', pricing: 'Free + from $12/month', bestFor: 'Game devs & creative professionals',
    features: ['Custom model training', 'Real-time canvas', 'Motion video generation', '10,000 daily tokens free'],
    pros: ['Most creative control', 'Generous free plan', 'Active community'],
    cons: ['Steep learning curve', 'Complex interface for beginners'],
  },
  {
    id: 'i3', slug: 'photoroom',
    name: 'PhotoRoom', tagline: 'AI product photography in seconds',
    description: 'PhotoRoom removes backgrounds and creates professional product photos with AI. Used by 150M+ users for e-commerce product photography.',
    category: Category.IMAGE, affiliateLink: 'https://photoroom.com/?via=yourlink',
    iconName: 'Crop', color: '#818cf8', accentColor: '#6366f1',
    userBadge: 'Free plan ✓', pricing: 'Free + $9.99/month', bestFor: 'E-commerce sellers',
    features: ['Background removal', 'AI background generation', 'Batch editing', 'Brand kits'],
    pros: ['Best background removal', 'Very fast', 'Great mobile app'],
    cons: ['Limited to photo editing', 'Watermark on free plan'],
  },
  {
    id: 'i15', slug: 'headshotpro',
    name: 'HeadshotPro', tagline: 'Professional AI headshots for remote teams',
    description: 'Get 120 professional headshots generated by AI from just 12 of your own photos. No photographer needed, no awkward photo sessions.',
    category: Category.IMAGE, affiliateLink: 'https://headshotpro.com?via=yourlink',
    iconName: 'User', color: '#06b6d4', accentColor: '#0891b2',
    userBadge: 'One-time price', pricing: 'From $29 one-time', bestFor: 'Professionals & remote teams',
    features: ['120 headshots per session', '40+ styles', 'Corporate & casual looks', '24hr turnaround'],
    pros: ['High quality output', 'One-time payment', 'No subscription needed'],
    cons: ['Results vary by input quality', 'Not real-time'],
  },

  // --- VIDEO ---
  {
    id: 'v1', slug: 'synthesia',
    name: 'Synthesia', tagline: 'Create AI videos with avatars from text',
    description: 'Synthesia creates professional AI videos from text in 120+ languages with photorealistic avatars. No camera, no microphone, no actors needed.',
    category: Category.VIDEO, affiliateLink: 'https://synthesia.io?via=yourlink',
    iconName: 'Video', color: '#f59e0b', accentColor: '#d97706',
    userBadge: 'Most popular', pricing: 'From $22/month', bestFor: 'Corporate trainers & marketers',
    features: ['160+ avatars', '120+ languages', 'Custom avatar', 'Screen recorder'],
    pros: ['Best avatar quality', 'Easy for non-techies', 'Multiple languages'],
    cons: ['No free plan', 'Avatars can look AI-ish'],
  },
  {
    id: 'v2', slug: 'pictory',
    name: 'Pictory', tagline: 'Turn articles and scripts into videos instantly',
    description: 'Pictory converts blog posts, scripts, and long-form content into short branded videos automatically. Great for content repurposing.',
    category: Category.VIDEO, affiliateLink: 'https://pictory.ai?via=yourlink',
    iconName: 'Film', color: '#818cf8', accentColor: '#6366f1',
    userBadge: 'Free trial ✓', pricing: 'From $19/month', bestFor: 'Bloggers & content repurposers',
    features: ['Article to video', 'Auto captions', 'Brand kit', 'AI voiceover'],
    pros: ['Saves hours of editing', 'Great for repurposing blogs', 'Easy to use'],
    cons: ['Limited customisation', 'AI voice sounds robotic'],
  },
  {
    id: 'v14', slug: 'opus-clip',
    name: 'Opus Clip', tagline: 'Repurpose long videos into viral shorts',
    description: 'Opus Clip uses AI to find the most engaging moments in your long videos and automatically turns them into short clips for TikTok, Reels, and YouTube Shorts.',
    category: Category.VIDEO, affiliateLink: 'https://opus.pro?via=yourlink',
    iconName: 'Crop', color: '#fbbf24', accentColor: '#d97706',
    userBadge: 'Free plan ✓', pricing: 'Free + from $19/month', bestFor: 'YouTubers & podcasters',
    features: ['AI clip selection', 'Auto captions', 'Virality score', 'Multi-platform export'],
    pros: ['Saves hours of editing', 'AI picks the best moments', 'Great free plan'],
    cons: ['Quality varies', 'Clips sometimes miss context'],
  },

  // --- AUDIO ---
  {
    id: 'a1', slug: 'elevenlabs',
    name: 'ElevenLabs', tagline: 'The most realistic AI voice generator',
    description: 'ElevenLabs generates the most realistic AI voices in 29 languages. Clone your own voice or choose from 900+ voices for audiobooks, videos, and apps.',
    category: Category.AUDIO, affiliateLink: 'https://elevenlabs.io/?via=yourlink',
    iconName: 'Mic', color: '#fbbf24', accentColor: '#d97706',
    userBadge: 'Free plan ✓', pricing: 'Free + from $5/month', bestFor: 'Content creators & developers',
    features: ['Voice cloning', '29 languages', '900+ voices', 'API access'],
    pros: ['Best voice quality by far', 'Generous free plan', 'Fast generation'],
    cons: ['Premium features expensive', 'Voice cloning requires samples'],
  },
  {
    id: 'a2', slug: 'murf-ai',
    name: 'Murf AI', tagline: 'Studio-quality AI voiceovers instantly',
    description: 'Murf AI lets you create studio-quality voiceovers for videos, presentations, and podcasts using 120+ AI voices across 20 languages.',
    category: Category.AUDIO, affiliateLink: 'https://murf.ai/?via=yourlink',
    iconName: 'Speaker', color: '#a78bfa', accentColor: '#7c3aed',
    userBadge: 'Free plan ✓', pricing: 'Free + from $19/month', bestFor: 'Video creators & eLearning',
    features: ['120+ voices', 'Voice changer', 'Background music', 'Video sync'],
    pros: ['Very natural voices', 'Easy video sync', 'Great for eLearning'],
    cons: ['Minute limits on plans', 'No voice cloning on basic plans'],
  },
  {
    id: 'a8', slug: 'podcastle',
    name: 'Podcastle', tagline: 'Record, edit & publish podcasts with AI',
    description: 'Podcastle offers studio-quality recording, AI-powered editing, and seamless exporting for podcasters. Record remotely and let AI handle the cleanup.',
    category: Category.AUDIO, affiliateLink: 'https://podcastle.ai?via=yourlink',
    iconName: 'Headphones', color: '#10b981', accentColor: '#059669',
    userBadge: 'Free plan ✓', pricing: 'Free + from $11.99/month', bestFor: 'Podcasters & interviewers',
    features: ['Remote recording', 'AI noise removal', 'Voice enhancement', 'Revoice (voice cloning)'],
    pros: ['All-in-one podcast tool', 'Great audio quality', 'Free plan available'],
    cons: ['Export limits on free plan', 'Less powerful than Descript'],
  },

  // --- MARKETING ---
  {
    id: 'm1', slug: 'adcreative-ai',
    name: 'AdCreative.ai', tagline: 'Generate conversion-focused ad creatives with AI',
    description: 'AdCreative.ai generates high-converting ad creatives and social media visuals trained on real ad performance data.',
    category: Category.MARKETING, affiliateLink: 'https://adcreative.ai/?via=yourlink',
    iconName: 'Megaphone', color: '#f43f5e', accentColor: '#e11d48',
    userBadge: 'Free trial ✓', pricing: 'From $21/month', bestFor: 'Performance marketers & agencies',
    features: ['AI ad generation', 'Performance scoring', 'Brand kits', 'Video ads'],
    pros: ['Trained on real ad data', 'Huge time saver', 'High CTR creatives'],
    cons: ['Not for organic content', 'Requires ad account data'],
  },
  {
    id: 'm2', slug: 'surfer-seo',
    name: 'Surfer SEO', tagline: 'Rank your content with data-driven SEO AI',
    description: 'Surfer SEO analyses top-ranking pages and tells you exactly how to optimise your content. Write, optimise, and audit SEO content with real-time scores.',
    category: Category.MARKETING, affiliateLink: 'https://surferseo.com/?via=yourlink',
    iconName: 'BarChart', color: '#fbbf24', accentColor: '#d97706',
    userBadge: 'SEO pick', pricing: 'From $89/month', bestFor: 'SEO professionals & agencies',
    features: ['Content editor', 'SERP analyser', 'Keyword research', 'Audit tool'],
    pros: ['Most accurate content scoring', 'Real ranking improvements', 'Best-in-class SEO tool'],
    cons: ['Expensive', 'Overkill for beginners'],
  },
  {
    id: 'm4', slug: 'ocoya',
    name: 'Ocoya', tagline: 'Create & schedule social media content 10x faster',
    description: 'Ocoya combines AI content creation with social media scheduling. Write captions, create visuals, and schedule posts to all platforms in one tool.',
    category: Category.MARKETING, affiliateLink: 'https://ocoya.com?via=yourlink',
    iconName: 'Share2', color: '#8b5cf6', accentColor: '#7c3aed',
    userBadge: 'Best for beginners', pricing: 'From $15/month', bestFor: 'Social media managers',
    features: ['AI caption writer', 'Visual creator', 'Multi-platform scheduling', 'Analytics'],
    pros: ['All-in-one social tool', 'Great value', 'Easy to use'],
    cons: ['Limited design flexibility', 'Scheduling can lag'],
  },
  {
    id: 'm11', slug: 'taplio',
    name: 'Taplio', tagline: 'Grow your LinkedIn audience with AI',
    description: 'Taplio is the all-in-one AI tool for LinkedIn growth. Generate post ideas, write viral content, schedule posts, and track performance — all powered by AI.',
    category: Category.MARKETING, affiliateLink: 'https://taplio.com?via=yourlink',
    iconName: 'User', color: '#3b82f6', accentColor: '#2563eb',
    userBadge: 'Most popular', pricing: 'From $39/month', bestFor: 'LinkedIn creators & founders',
    features: ['AI post writer', 'Viral post database', 'Lead finder', 'Analytics'],
    pros: ['Best LinkedIn growth tool', 'Huge inspiration library', 'Strong community'],
    cons: ['LinkedIn only', 'Expensive for beginners'],
  },

  // --- DESIGN ---
  {
    id: 'd2', slug: 'beautiful-ai',
    name: 'Beautiful.ai', tagline: 'AI presentation software that designs for you',
    description: 'Beautiful.ai uses AI to automatically design presentation slides. Just type your content and the AI handles layout, alignment, and visual consistency.',
    category: Category.DESIGN, affiliateLink: 'https://beautiful.ai/?via=yourlink',
    iconName: 'Layout', color: '#f472b6', accentColor: '#db2777',
    userBadge: 'Free trial ✓', pricing: 'From $12/month', bestFor: 'Business professionals',
    features: ['Smart slide templates', 'AI design suggestions', 'Team collaboration', 'Brand controls'],
    pros: ['Slides always look professional', 'Fast to create', 'Great team features'],
    cons: ['Less flexible than Canva', 'Limited free tier'],
  },
  {
    id: 'd3', slug: 'looka',
    name: 'Looka', tagline: 'Design your brand logo with AI',
    description: 'Looka uses AI to generate professional logos and brand identities. Answer a few questions about your brand and get hundreds of logo options instantly.',
    category: Category.DESIGN, affiliateLink: 'https://looka.com?via=yourlink',
    iconName: 'PenTool', color: '#3b82f6', accentColor: '#2563eb',
    userBadge: 'One-time price', pricing: 'From $20 one-time', bestFor: 'Startups & small businesses',
    features: ['AI logo generation', 'Brand kit', 'Business card design', 'Social media assets'],
    pros: ['Professional quality logos', 'Huge variety of styles', 'One-time payment option'],
    cons: ['Less unique than custom design', 'Editing limited after purchase'],
  },
  {
    id: 'd8', slug: 'gamma',
    name: 'Gamma', tagline: 'Build beautiful decks & docs with AI',
    description: 'Gamma is a new way to present ideas. Build beautiful presentations, documents, and webpages powered by AI — no design skills needed.',
    category: Category.DESIGN, affiliateLink: 'https://gamma.app?via=yourlink',
    iconName: 'Layout', color: '#c084fc', accentColor: '#9333ea',
    userBadge: 'Free plan ✓', pricing: 'Free + from $8/month', bestFor: 'Founders & educators',
    features: ['AI deck builder', 'One-click restyling', 'Embeds & interactivity', 'Web publishing'],
    pros: ['Stunning output instantly', 'Very easy to use', 'Great free plan'],
    cons: ['Less control than PowerPoint', 'Gamma branding on free plan'],
  },

  // --- CODING ---
  {
    id: 'c3', slug: 'tabnine',
    name: 'Tabnine', tagline: 'AI code completion for every IDE',
    description: 'Tabnine is an AI code completion tool that learns your codebase and anticipates your next coding move. Supports all major languages and IDEs.',
    category: Category.CODING, affiliateLink: 'https://tabnine.com/?via=yourlink',
    iconName: 'Code2', color: '#818cf8', accentColor: '#6366f1',
    userBadge: 'Free plan ✓', pricing: 'Free + from $12/month', bestFor: 'Professional developers',
    features: ['Codebase learning', 'Whole-line completion', 'Privacy mode', 'All major IDEs'],
    pros: ['Learns your coding style', 'Privacy-first option', 'Works offline'],
    cons: ['Less capable than Copilot', 'Needs time to learn your codebase'],
  },
  {
    id: 'c7', slug: 'replit',
    name: 'Replit', tagline: 'Build & deploy apps with AI in your browser',
    description: 'Replit is a browser-based IDE with powerful AI features. Build, run, and deploy full applications with AI assistance — no setup required.',
    category: Category.CODING, affiliateLink: 'https://replit.com?via=yourlink',
    iconName: 'Terminal', color: '#f43f5e', accentColor: '#e11d48',
    userBadge: 'Free plan ✓', pricing: 'Free + from $7/month', bestFor: 'Students & indie developers',
    features: ['AI coding assistant', 'Instant deployment', 'Multiplayer coding', '50+ languages'],
    pros: ['Zero setup', 'Great for learning', 'Instant hosting'],
    cons: ['Slower than local IDEs', 'Free tier has limits'],
  },

  // --- PRODUCTIVITY ---
  {
    id: 'p1', slug: 'notion-ai',
    name: 'Notion AI', tagline: 'AI built right inside your workspace',
    description: 'Notion AI gives you the power of AI directly inside your notes, docs, and wikis. Summarise, write, translate, and automate tasks without leaving your workspace.',
    category: Category.PRODUCTIVITY, affiliateLink: 'https://notion.so/?via=yourlink',
    iconName: 'FileText', color: '#6366f1', accentColor: '#4f46e5',
    userBadge: 'Most popular', pricing: '$10/month add-on', bestFor: 'Teams & knowledge workers',
    features: ['AI writing in docs', 'Auto-summarise', 'Action items from meetings', 'Database AI fills'],
    pros: ['Built into your existing workflow', 'Great for teams', 'Very versatile'],
    cons: ['Requires Notion subscription', 'AI is an add-on cost'],
  },
  {
    id: 'p2', slug: 'otter-ai',
    name: 'Otter.ai', tagline: 'AI meeting notes & transcription automatically',
    description: 'Otter.ai automatically records, transcribes, and summarises your meetings. Works with Zoom, Google Meet, and Microsoft Teams.',
    category: Category.PRODUCTIVITY, affiliateLink: 'https://otter.ai/?via=yourlink',
    iconName: 'ListMusic', color: '#f87171', accentColor: '#ef4444',
    userBadge: 'Free plan ✓', pricing: 'Free + from $10/month', bestFor: 'Remote teams & managers',
    features: ['Auto meeting notes', 'Action item extraction', 'Meeting summaries', 'Zoom/Meet/Teams integration'],
    pros: ['Saves hours per week', 'Accurate transcription', 'Great free plan'],
    cons: ['Needs meeting bot access', 'Accuracy drops with accents'],
  },
  {
    id: 'p3', slug: 'taskade',
    name: 'Taskade', tagline: 'AI-powered tasks, projects & team collaboration',
    description: 'Taskade combines AI task management, project planning, and team chat in one workspace. Build AI agents to automate your workflows.',
    category: Category.PRODUCTIVITY, affiliateLink: 'https://taskade.com/?via=yourlink',
    iconName: 'CheckSquare', color: '#ec4899', accentColor: '#db2777',
    userBadge: 'Free plan ✓', pricing: 'Free + from $8/month', bestFor: 'Freelancers & small teams',
    features: ['AI task generation', 'Custom AI agents', 'Video collaboration', 'Mind maps'],
    pros: ['Very feature-rich', 'Great free plan', 'Covers tasks + chat'],
    cons: ['Can feel overwhelming', 'Mobile app needs work'],
  },
  {
    id: 'p5', slug: 'fireflies-ai',
    name: 'Fireflies.ai', tagline: 'Auto-record, transcribe & analyse every meeting',
    description: 'Fireflies.ai automatically records and transcribes your meetings, then lets you search, clip, and share key moments. Works with all major video conferencing tools.',
    category: Category.PRODUCTIVITY, affiliateLink: 'https://fireflies.ai/?via=yourlink',
    iconName: 'Bot', color: '#60a5fa', accentColor: '#2563eb',
    userBadge: 'Free plan ✓', pricing: 'Free + from $10/month', bestFor: 'Sales teams & remote workers',
    features: ['Auto recording', 'Smart search', 'Clip sharing', 'CRM integrations'],
    pros: ['Works with all major platforms', 'Great search', 'Strong free plan'],
    cons: ['Privacy concerns for some users', 'Transcription not perfect'],
  },
];
