// blog/types.ts
// Shared type for all blog posts in AI Nexus

export interface BlogPost {
  slug: string;
  title: string;
  /** ≤49 chars — used as <title> tag (appended with " | AI Nexus"). Falls back to title if absent. */
  seoTitle?: string;
  metaDescription: string;
  datePublished: string;  // YYYY-MM-DD
  dateModified: string;   // YYYY-MM-DD
  author: string;
  category: string;
  readTime: string;
  excerpt: string;
  /** Full article body as an HTML string */
  content: string;
  /** FAQ pairs — rendered as FAQPage JSON-LD schema + visible Q&A section */
  faqs: { q: string; a: string }[];
  /**
   * Optional per-post Open Graph image URL.
   * When set, resolveOgImage() uses this instead of the generic category-level
   * image (og-blog-writing.webp / og-blog-audio.webp / og-blog-video.webp).
   * Convention: `${SITE}/og/blog/<slug>.webp`
   * Generated by: node scripts/generate-blog-og-images.mjs
   */
  ogImage?: string;
}
